SELECT ITEMNO, DESCRIPTION, WEIGHT
FROM ITEMS
WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);


SELECT WID, WNAME
FROM WAREHOUSES
WHERE LOCATION = 'Pune';

SELECT I.ITEMNO, I.DESCRIPTION, O.ODATE
FROM ITEMS I
JOIN ORDERS_ITEMS OI ON I.ITEMNO = OI.ITEMNO
JOIN ORDERS O ON OI.ONO = O.ONO
JOIN CUSTOMER C ON O.CNO = C.CNO
WHERE C.CNAME = 'Patil';

SELECT W.WID, W.WNAME, COUNT(S.SID) AS StoreCount
FROM WAREHOUSES W
JOIN STORES S ON W.LOCATION = S.LOCATION_cITY
GROUP BY W.WID, W.WNAME
ORDER BY StoreCount DESC
LIMIT 1;


SELECT I.ITEMNO, I.DESCRIPTION, COUNT(OI.ITEMNO) AS OrderCount
FROM ITEMS I
LEFT JOIN ORDERS_ITEMS OI ON I.ITEMNO = OI.ITEMNO
GROUP BY I.ITEMNO, I.DESCRIPTION
ORDER BY OrderCount ASC
LIMIT 1;

SELECT C.CNO, C.CNAME, O.ONO, O.ODATE, I.DESCRIPTION, OI.ORDERED_QUANTITY
FROM CUSTOMER C
JOIN ORDERS O ON C.CNO = O.CNO
JOIN ORDERS_ITEMS OI ON O.ONO = OI.ONO
JOIN ITEMS I ON OI.ITEMNO = I.ITEMNO;




